# Generated by Django 3.2.7 on 2023-03-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_userdetails_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='pincode',
            field=models.CharField(default=0, max_length=6),
        ),
    ]
